language: csharp
sudo: required
dist: trusty
env:
  - CLI_VERSION="2.0.0-preview1-005660"
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
mono:
  - latest
os:
  - linux
osx_image: xcode7.1
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - dotnet restore
  - dotnet build src/GraphQLCore
  - dotnet build test/GraphQLCore.Tests
  - cd test/GraphQLCore.Tests
  - dotnet run
